### ISSUE TITLE
ActiveRecord::StatementInvalid in JobsController#create

### ISSUE THREAD

**Issue by erikasland** [kellybhoward/landit#1]
**_When I try to create a job using the following urI..._**

`http://jobview.monster.com/GetJob.aspx?JobID=165259542&aid=137865303&uid=100010CABF7D4B2C1FBC9E776D9C2790CDD9E3E83A14F38638951245703327D0928C480FBAEE3CD226D92BAA5B35D343E3C5D3B4A1FC8B8C97AB213445B4E288B589C790D5DBCA95C05316912FCD2FA488F00C&WT.mc_n=PSAAHG10_app_jv_p&jvs=e,ar,t,1`

**_I get the following error..._**
![error](https://cloud.githubusercontent.com/assets/12867686/14052996/6d6bd436-f29c-11e5-86d7-3905e74479d9.png)

**Comment by kellybhoward** [comment]
Yes - thanks for the heads up. I'm implementing a ruby gem to shorten urls before storing them in my DB. At the moment, it's a string length error. Will fix ASAP.

**Comment by erikasland** [comment]
Killer. Thanks!

**Comment by kellybhoward** [comment]
Fixed!
